<?php

return [
    "module_name" => [
        "single" => "Nieuws",
        "multiple" => "Nieuws"
    ],
    "fields" => [
        "uploads" => [
            "active" => true,
            "type" => "",
            "title" => "Uploads",
            "read" => false,
            "required" => false,
            "edit" => false,
        ],
        "locale" => [
            "active" => true,
            "type" => "text",
            "title" => "Taal",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "newscat" => [
            "active" => false,
            "type" => "checklist",
            "title" => "Categorieën",
            "options" => [],
            "read" => true,
            "value" => null,
            "required" => false,
            "edit" => false,
        ],
        "author" => [
            "active" => false,
            "type" => "text",
            "title" => "Auteur",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "title" => [
            "active" => true,
            "type" => "text",
            "title" => "Titel",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "title_2" => [
            "active" => false,
            "type" => "text",
            "title" => "Titel 2",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "title_3" => [
            "active" => false,
            "type" => "text",
            "title" => "Titel 3",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "slug" => [
            "active" => false,
            "type" => "text",
            "title" => "Slug",
            "required" => true,
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "seo_title" => [
            "active" => false,
            "type" => "text",
            "title" => "SEO Titel",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "seo_description" => [
            "active" => false,
            "type" => "textarea",
            "title" => "SEO Omschrijving",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "tags" => [
            "active" => false,
            "type" => "textarea",
            "title" => "Tags",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "summary" => [
            "active" => false,
            "type" => "textarea",
            "title" => "Opsomming",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "excerpt" => [
            "active" => false,
            "type" => "textarea",
            "title" => "Inleiding",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "content" => [
            "active" => true,
            "type" => "editor",
            "title" => "Content",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
    ]
];
