<?php

return [
    "module_name" => [
        "single" => "Nieuws categorie",
        "multiple" => "Nieuws categorieën"
    ],
    "fields" => [
        "uploads" => [
            "active" => false,
            "type" => "",
            "title" => "Uploads",
            "read" => false,
            "required" => false,
        ],
        "locale" => [
            "active" => false,
            "type" => "text",
            "title" => "Taal",
            "read" => true,
            "required" => false,
        ],
        "active" => [
            "active" => false,
            "type" => "boolean",
            "title" => "Actief",
            "read" => true,
            "required" => true,
        ],
        "company_id" => [
            "active" => false,
            "type" => "integer",
            "title" => "Bedrijf ID",
            "read" => true,
            "required" => false,
        ],
        "host" => [
            "active" => false,
            "type" => "text",
            "title" => "Host",
            "read" => true,
            "required" => false,
        ],
        "sort" => [
            "active" => false,
            "type" => "integer",
            "title" => "Sorteer",
            "read" => true,
            "required" => true,
        ],
        "newscat_id" => [
            "active" => false,
            "type" => "integer",
            "title" => "Nieuws categorie ID",
            "read" => true,
            "required" => false,
        ],
        "title" => [
            "active" => true,
            "type" => "text",
            "title" => "Titel",
            "read" => true,
            "required" => true,
        ],
        "title_2" => [
            "active" => false,
            "type" => "text",
            "title" => "Titel 2",
            "read" => true,
            "required" => false,
        ],
        "title_3" => [
            "active" => false,
            "type" => "text",
            "title" => "Titel 3",
            "read" => true,
            "required" => false,
        ],
        "slug" => [
            "active" => false,
            "type" => "text",
            "title" => "Slug",
            "read" => true,
            "required" => false,
        ],
        "seo_title" => [
            "active" => false,
            "type" => "text",
            "title" => "SEO Titel",
            "read" => true,
            "required" => false,
        ],
        "seo_description" => [
            "active" => false,
            "type" => "text",
            "title" => "SEO Beschrijving",
            "read" => true,
            "required" => false,
        ],
        "tags" => [
            "active" => false,
            "type" => "text",
            "title" => "Tags",
            "read" => true,
            "required" => false,
        ],
        "summary" => [
            "active" => false,
            "type" => "textarea",
            "title" => "Samenvatting",
            "read" => true,
            "required" => false,
        ],
        "excerpt" => [
            "active" => false,
            "type" => "textarea",
            "title" => "Uittreksel",
            "read" => true,
            "required" => false,
        ],
        "content" => [
            "active" => false,
            "type" => "textarea",
            "title" => "Inhoud",
            "read" => true,
            "required" => false,
        ],
        "administration" => [
            "active" => false,
            "type" => "text",
            "title" => "Administratie",
            "read" => true,
            "required" => false,
        ],
        "identifier" => [
            "active" => false,
            "type" => "text",
            "title" => "Identifier",
            "read" => true,
            "required" => false,
        ],
    ]
];
